apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: executor-3
  template:
    metadata:
      labels:
        app: executor-3
    spec:
      initContainers:
      - name: wait-for-executor-2
        image: curlimages/curl:latest
        command:
        - "sh"
        - "-c"
        - |
          until curl -sf http://executor-2-service.iosis-tech-zetina.svc.cluster.local:3000/health | grep -q "Health check: OK"; do
            echo "Waiting for executor-2 to be ready..."
            sleep 1
          done
      containers:
      - name: executor-3
        image: registry.internal.iosis.tech/zetina-executor:latest
        args: ["bash", "-ci", "cargo run --release --bin zetina-executor -- -l /ip4/0.0.0.0/tcp/5683 -p $(PRIVATE_KEY) -a $(ADDRESS) -d $(DIAL)"]
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "4"
            memory: "10Gi"
        env:
        - name: RUST_LOG
          valueFrom:
            configMapKeyRef:
              name: zetina-config
              key: RUST_LOG
        - name: CAIRO_PATH
          valueFrom:
            configMapKeyRef:
              name: zetina-config
              key: CAIRO_PATH
        - name: BOOTLOADER_PATH
          valueFrom:
            configMapKeyRef:
              name: zetina-config
              key: BOOTLOADER_PATH
        - name: BOOTLOADER_OUT_NAME
          valueFrom:
            configMapKeyRef:
              name: zetina-config
              key: BOOTLOADER_OUT_NAME
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: zetina-secret
              key: PRIVATE_KEY_3
        - name: ADDRESS
          valueFrom:
            secretKeyRef:
              name: zetina-secret
              key: ADDRESS_3
        - name: DIAL
          valueFrom:
            secretKeyRef:
              name: zetina-secret
              key: ADDRESS_2
        ports:
        - containerPort: 3000
        - containerPort: 5682
        - containerPort: 5683
---
apiVersion: v1
kind: Service
metadata:
  name: executor-3-service
  annotations:
    kube-vip.io/loadbalancerIPs: "0.0.0.0"
    kube-vip.io/hwaddr: "00:00:6C:32:98:84"
    kube-vip.io/loadbalancerHostname: "zetina-executor-3"
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: api-port
  - port: 5682
    targetPort: 5682
    protocol: UDP
    name: p2p-quic-port
  - port: 5683
    targetPort: 5683
    protocol: TCP
    name: p2p-tcp-port
  selector:
    app: executor-3
  type: LoadBalancer
