apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zetina-delegator-cert
spec:
  secretName: zetina-tls

  dnsNames:
  - dashboard.delegator.zetina.iosis.tech
  issuerRef:
    name: letsencrypt-http01
    kind: Issuer
