services:
  zetina-stone-prover:
    build:
      context: stone-prover
      dockerfile: Dockerfile
    image: zetina-stone-prover

  zetina-runtime:
    build:
      dockerfile: runtime.dockerfile
    image: zetina-runtime
    depends_on:
      - zetina-stone-prover

  zetina-delegator:
    build:
      dockerfile: delegator.dockerfile
    image: zetina-delegator
    hostname: zetina-delegator
    depends_on:
      - zetina-runtime
      - zetina-executor
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: '10G'
    environment:
      - RUST_LOG=info
    networks:
      zetina-network:
        ipv4_address: 172.16.238.3
    ports:
      - "3010:3010"
    command: ["bash", "-ci", "cargo run --release --bin zetina-delegator -- -p 018ef9563461ec2d88236d59039babf44c97d8bf6200d01d81170f1f60a78f32 -d /ip4/172.16.238.2/tcp/5679/p2p/QmVUbnW8PjFw2yUt1DDukUTZrK1t2vPGkNb1SQgserjaXV"]

  zetina-executor:
    build:
      dockerfile: executor.dockerfile
    image: zetina-executor
    depends_on:
      - zetina-runtime
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: '10G'
    environment:
      - RUST_LOG=info
    networks:
      zetina-network:
        ipv4_address: 172.16.238.2
    command: ["bash", "-ci", "cargo run --release --bin zetina-executor -- -p 018ef9563461ec2d88236d59039babf44c97d8bf6200d01d81170f1f60a78f31"]

networks:
  zetina-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24