services:
  zetina-stone-prover:
    build:
      context: stone-prover
      dockerfile: Dockerfile
    image: zetina-stone-prover

  zetina-runtime:
    build:
      dockerfile: runtime.dockerfile
    image: zetina-runtime
    depends_on:
      - zetina-stone-prover

  zetina-delegator:
    build:
      dockerfile: delegator.dockerfile
    image: zetina-delegator
    depends_on:
      - zetina-runtime
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: '10G'
    environment:
      - RUST_LOG=info
    networks:
      - zetina-network

  zetina-delegator-dashboard:
    build:
      context: dashboard
      dockerfile: dashboard.dockerfile
    image: zetina-delegator-dashboard
    depends_on:
      - zetina-delegator
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
    ports:
      - "3000:3000/tcp"
    environment:
      - NEXT_PUBLIC_API_URL=http://zetina-delegator:3010
    networks:
      - zetina-network

  zetina-executor:
    build:
      dockerfile: executor.dockerfile
    image: zetina-executor
    depends_on:
      - zetina-runtime
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: '10G'
    environment:
      - RUST_LOG=info
    networks:
      - zetina-network

networks:
  zetina-network:
    driver: bridge