services:
  zetina-stone-prover:
    build:
      context: stone-prover
      dockerfile: Dockerfile
    image: zetina-stone-prover

  zetina-runtime:
    build:
      dockerfile: runtime.dockerfile
    image: zetina-runtime
    depends_on:
      - zetina-stone-prover

  zetina-delegator-1:
    build:
      dockerfile: delegator.dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
    environment:
      - RUST_LOG=info
    image: zetina-delegator
    hostname: zetina-delegator-1
    networks:
      zetina-network:
        ipv4_address: 172.16.238.2
    ports:
      - "4000:3000"
    command:
      - "bash"
      - "-ci"
      - "cargo run --release --bin zetina-delegator -- -l /ip4/0.0.0.0/tcp/5679  -p ${PRIVATE_KEY_1} -a /ip4/172.16.238.2/tcp/5679/p2p/${PEER_ID_1}"

  zetina-executor-1:
    build:
      dockerfile: executor.dockerfile
    depends_on:
      - zetina-runtime
      - zetina-delegator-1
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: '25G'
    environment:
      - RUST_LOG=info
    image: zetina-executor
    hostname: zetina-executor-1
    networks:
      zetina-network:
        ipv4_address: 172.16.238.12
    command:
      - "bash"
      - "-ci"
      - "cargo run --release --bin zetina-executor -- -l /ip4/0.0.0.0/tcp/5679 -p ${PRIVATE_KEY_2} -a /ip4/172.16.238.12/tcp/5679/p2p/${PEER_ID_2} -d /ip4/172.16.238.2/tcp/5679/p2p/${PEER_ID_1}"

  zetina-executor-2:
    build:
      dockerfile: executor.dockerfile
    depends_on:
      - zetina-runtime
      - zetina-delegator-1
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: '25G'
    environment:
      - RUST_LOG=info
    image: zetina-executor
    hostname: zetina-executor-2
    networks:
      zetina-network:
        ipv4_address: 172.16.238.13
    command:
      - "bash"
      - "-ci"
      - "cargo run --release --bin zetina-executor -- -l /ip4/0.0.0.0/tcp/5679 -p ${PRIVATE_KEY_3} -a /ip4/172.16.238.13/tcp/5679/p2p/${PEER_ID_3} -d /ip4/172.16.238.2/tcp/5679/p2p/${PEER_ID_1}"

networks:
  zetina-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
