services:
  zetina-stone-prover:
    build:
      context: stone-prover
      dockerfile: Dockerfile
    image: zetina-stone-prover

  zetina-runtime:
    build:
      dockerfile: runtime.dockerfile
    image: zetina-runtime
    depends_on:
      - zetina-stone-prover

  zetina-delegator:
    build:
      dockerfile: delegator.dockerfile
    image: zetina-delegator
    depends_on:
      - zetina-runtime
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: '10G'
    ports:
      - "3010:3010/tcp"
    environment:
      - RUST_LOG=info
    networks:
      - zetina-network

  zetina-executor:
    build:
      dockerfile: executor.dockerfile
    image: zetina-executor
    depends_on:
      - zetina-runtime
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: '10G'
    environment:
      - RUST_LOG=info
    networks:
      - zetina-network

networks:
  zetina-network:
    driver: bridge