services:
  stone-prover:
    build:
      context: stone-prover
      dockerfile: Dockerfile
    image: stone-prover

  runtime:
    build:
      dockerfile: runtime.dockerfile
    image: runtime
    depends_on:
      - stone-prover

  delegator:
    build:
      dockerfile: delegator.dockerfile
    depends_on:
      - runtime
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: '10G'
    ports:
      - "3010:3010/tcp"
    environment:
      - RUST_LOG=info
    networks:
      - zetina-network

  executor:
    build:
      dockerfile: executor.dockerfile
    depends_on:
      - runtime
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: '10G'
    ports:
      - "3020:3020/tcp"
    environment:
      - RUST_LOG=info
    networks:
      - zetina-network

networks:
  zetina-network:
    driver: bridge