services:
  zetina-stone-prover:
    build:
      context: stone-prover
      dockerfile: Dockerfile
    image: zetina-stone-prover

  zetina-runtime:
    build:
      dockerfile: runtime.dockerfile
    image: zetina-runtime
    depends_on:
      - zetina-stone-prover

  zetina-delegator:
    build:
      dockerfile: delegator.dockerfile
    image: zetina-delegator
    hostname: zetina-delegator
    depends_on:
      - zetina-runtime
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: '10G'
    environment:
      - RUST_LOG=info
    networks:
      - zetina-network
    ports:
      - "3010:3010"
    command: "bash -c cargo run --release --bin zetina-delegator -- -p 018ef9563461ec2d88236d59039babf44c97d8bf6200d01d81170f1f60a78f31"

  zetina-delegator-dashboard:
    build:
      context: dashboard
      dockerfile: dashboard.dockerfile
    image: zetina-delegator-dashboard
    depends_on:
      - zetina-delegator
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
    ports:
      - "3000:3000/tcp"
    networks:
      - zetina-network

  zetina-executor:
    build:
      dockerfile: executor.dockerfile
    image: zetina-executor
    depends_on:
      - zetina-runtime
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: '10G'
    environment:
      - RUST_LOG=info
    networks:
      - zetina-network
    command: "bash -c cargo run --release --bin zetina-executor -- -p 018ef9563461ec2d88236d59039babf44c97d8bf6200d01d81170f1f60a78f32 -d /ip4/zetina-delegator/tcp/5679/p2p/QmVUbnW8PjFw2yUt1DDukUTZrK1t2vPGkNb1SQgserjaXV"

networks:
  zetina-network:
    driver: bridge