apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
  - image: registry.internal.iosis.tech/zetina-executor
    context: .
    docker:
      dockerfile: executor.dockerfile
manifests:
  rawYaml:
  - ./k8s/executor-deployment-1.yaml
  - ./k8s/executor-deployment-2.yaml
  - ./k8s/executor-deployment-3.yaml
