
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delegator
spec:
  selector:
    matchLabels:
      app: delegator
  replicas: 1
  template:
    metadata:
      labels:
        app: delegator
    spec:
      containers:
      - name: delegator
        image: registry.internal.iosis.tech/zetina-delegator
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "10"
            memory: "10Gi"
        env:
        - name: RUST_LOG
          value: "info"
        ports:
        - containerPort: 3010
---
apiVersion: v1
kind: Service
metadata:
  name: delegator-service
spec:
  selector:
    app: delegator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3010
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delegator-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 0
spec:
  ingressClassName: nginx-ingress-prod
  tls:
  - hosts:
    - delegator.zetina.iosis.tech
    secretName: zetina-delegator-tls
  rules:
  - host: delegator.zetina.iosis.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: delegator-service
            port:
              number: 80
