
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delegator
  namespace: zetina
spec:
  selector:
    matchLabels:
      app: delegator
  replicas: 1
  template:
    metadata:
      labels:
        app: delegator
    spec:
      containers:
      - name: delegator
        image: registry.internal.iosis.tech/zetina-delegator
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "10"
            memory: "10Gi"
        env:
        - name: RUST_LOG
          value: "info"
        ports:
        - containerPort: 3010
---
apiVersion: v1
kind: Service
metadata:
  name: delegator-service
  namespace: zetina
spec:
  selector:
    app: delegator
  ports:
  - protocol: TCP
    port: 3010
    targetPort: 3010
